import React from 'react'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.bundle.min.js'; 
import '../components/pages.css'
import about from '../Images/about.webp';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import captain from '../Images/person.jpg';
import vice from '../Images/vice.jpg';
import {  useInView } from 'react-intersection-observer';

export default function About() {
  const[ref,inView] = useInView({
    triggerOnce:true,
    threshold:0.2,
  });
  return (
    <div>
      <Navbar/>
      <div className='about-content'><br></br>
      <h2 className='about-heading2'>We are a boutique council of Sri Lanka focused on creating better environmental experiences.</h2>
      <h1 className='about-heading3'>Let's clean our city. Be prepared</h1>
      </div>
      <div className='about'>
        <div class="card mb-3 position-absolute top-50 start-50 translate-middle" style={{width:800}}>
            <div class="row g-0">
                 <div class="col-md-4">
                       <img src={about}class="img-fluid rounded-start" alt="..."/>
                 </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">About Us</h5>
                        <p class="card-text">Garbage collection is the process of collecting, transporting, and disposing of waste materials generated by households, businesses, and other entities. This process is crucial for maintaining clean and healthy environments, preventing pollution and diseases, and preserving natural resources. Garbage collection services are typically provided by local governments or private waste management companies, who use specialized vehicles and equipment to collect and transport the waste to designated disposal sites, such as landfills or recycling facilities. The collection schedule and fees may vary depending on the location and type of service, but in general, garbage collection is an essential service that plays a critical role in maintaining the quality of life for communities.</p>
                       
                </div>
             </div>
           </div>
        </div>
      </div>
      
      <div className='mission'>
        <div className='mission-content'>
            <h1 className='head'>Our Mission</h1>
            <h2 className='text'>To protect the environment through sustainable initiatives, the Green Task Force fosters community engagement, drives impactful change, and promotes eco-conscious practices for a greener and healthier planet</h2>
             
        </div>
      </div>
      <div className='vision'>
        <div className='vision-content'>
            <h1 className='vision-head'>Our Vision</h1>
            <h2 className='vision-text'>A greener world where nature thrives, communities coexist sustainably.The Green Force leads Force leads global climate efforts, inspiring eco-policies for a resilient planet.</h2>
           
           
           
           
           
             
        </div>
      </div>

    <div ref={ref} className={inView?'captain slideUp':'captain'}>
      <div class="card mb-3 bg-$green-light" style={{width:600}}>
    <div class="row g-0">
  
    <div class="col-md-8">
      <div class="card-body">
        
        <p class="card-text">“Green mountains are always the centre of attraction, and we find peace by visiting them, so please do not despoil this beauty by throwing trash, and keep it clean.”</p>
        <p>-Green Captain</p>
      </div>
    </div>
    <div class="col-md-4">
      <img src={captain} class="img-fluid rounded-start" alt="..."/>
    </div>
  </div>
</div>
</div>

<div ref={ref} className={inView ?'vice slideup':'vice'}>
<div class="card mb-3 bg-$green-light" style={{width:600}}>
    <div class="row g-0">
    <div class="col-md-4">
      <img src={vice} class="img-fluid rounded-start" alt="..."/>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        
        <p class="card-text">“If we want clean air, we must keep the earth green, so we must maintain strict environmental cleanliness.”</p>
        <p>-Green vice Captain</p>
      </div>
    </div>
   
  </div>
</div>
</div>
    <Footer/>
    </div>
  )
}
